### ISSUE TITLE
Warnings during install of latest version

### ISSUE THREAD

**Issue by ghost** [sbozarth/homebridge-lc7001#12]
Long time user...not sure if this is an issue or not, but I did see the following warnings during upgrade to the latest version.

-Installed using sudo -E -n npm install -g homebridge-lc7001@latest
-Latest version on NPM is 1.1.2, however the @latest command seems to be trying to install 1.1.1
-The I see 2 NPM warnings...see below

CMD: sudo -E -n npm install -g homebridge-lc7001@latest

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/homebridge-lc7001 failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN homebridge-lc7001@1.1.1 requires a peer of homebridge@>=1.1.0 but none is installed. You must install peer dependencies yourself.

+ homebridge-lc7001@1.1.1
updated 1 package in 169.355s

Command succeeded!.

**Comment by sbozarth** [comment]
I’m no expert on NPM and so I don’t know if there is much for me to contribute. I don’t think this is an issue with the plug-in; just NPM.

As best I can tell a DNS lookup error occurred trying to lookup registry.npmjs.org. This might be why 1.1.1 was used instead of 1.1.2. The second error suggests homebridge is not installed or at least not installed through NPM.

If there is something wrong with how I published to NPM, I’m happy to take a look. I just really know nothing about it; I just followed some examples and hoped for the best.

I would verify you can lookup that domain name and try again.

**Comment by ghost** [comment]
Thanks, I updated both Node and NPM on my R Pi yesterday. then uninstalled and reinstalled the package and everything seems fine now. The view from Homebridge UI X:Homebridge Lc7001
homebridge-lc7001 v1.2.0
